server:
  port: 8082
  servlet:
    context-path: /inventory

spring:
  application:
    name: inventory-service
  sleuth:
    sampler:
      percentage: 1.0
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
  datasource:
    name: inventorydb
  boot:
    admin:
      client:
        url: http://localhost:7777/admin
  main:
    allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: false

spring.zipkin.base-url: http://localhost:9411/
